blog/urls.py
# urls.py

from django.conf.urls import url, include
from blog import views

app_name = 'blog'

urlpatterns = [
	url(r'home', views.HomeView.as_view(), name='home'),
	url(r'about', views.AboutView.as_view(), name='about'),
	url(r'contactus', views.ContatView.as_view(), name='contactus'),
	url(r'notificatios', views.GetNotifications.as_view(), name='notofications'),
	url(r'get_fields', views.GetColumnData.as_view(), name='get_fields'),

	url(r'^post/post_list', views.GetPostList.as_view()),
	url(r'^post/(?P<slug>[-\w]+)$', views.DetailPostView.as_view(), name='post_details'),
	url(r'post/comment/add_comment$', views.AddComment.as_view(), name='add_comment'),
	url(r'post/comment/update_comment$', views.CommentActions.as_view(), name='update_comment'),
	url(r'^post/edit/(?P<pk>\d+)$', views.EditBlogView.as_view(), name='edit_blog'),
	url(r'^post/update/(?P<pk>\d+)$', views.UpdateBlogView.as_view(), name='update_blog'),
	url(r'post/comment/add_update_subcomment', views.SubCommentActions.as_view(), name='sub_comment'),

	url(r'create', views.CreateBlogView.as_view(), name='create'),
	url(r'drafts$', views.DraftView.as_view(), name='drafts'),
	url(r'delete_post/(?P<pk>\d+)$', views.DeletePostView.as_view(), name='delete_post'),
	url(r'draft_details', views.GetDraftDetails.as_view(), name='dtaft_details'),
	url(r'update_draft', views.UpdateDraft.as_view(), name='update_draft'),
	url(r'my_blogs', views.MyTechBlogs.as_view(), name='my_blogs'),
	url(r'^get_tags/', views.GetBlogTags.as_view(), name='get_tags'),
	

]

tech_blog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf.urls.static import static
from blog import urls
from user_auth import urls as auth_urls
from django.conf import settings
from blog import views
import blog


urlpatterns = [
    url(r'^$', views.HomeView.as_view()),
    path('admin/', admin.site.urls),
    url(r'blog/', include(urls)),
	url(r'user/', include(auth_urls))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'blog.views.handler404'
handler500 = 'blog.views.handler500'

user_auth/urls.py
#urls.py

from django.conf.urls import url
from user_auth import views

app_name = 'user'

urlpatterns = [
	url(r'login', views.LoginView.as_view(), name="login"),
	url(r'logout', views.LogoutView.as_view(), name="logout"),
	url(r'user_details/(?P<slug>[-\w]+)', views.UserDetailsView.as_view(), name="user_details"),
	url(r'update_password', views.UpdatePasswordView.as_view(), name="update_password"),
	url(r'register', views.RegisterView.as_view(), name="register"),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.db.models.signals import post_save, post_delete, pre_save
from slugify import slugify

# Create your models here.

MESSAGE_TYPE = (
	('comment', 'comment'),
	('post', 'post'),
	('profile', 'profile')
)

class Post(models.Model):
	author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
	title = models.CharField(max_length=200, unique=True)
	text = models.TextField()
	created_date = models.DateTimeField( auto_now_add=True)
	published_date = models.DateTimeField(blank=True, null=True)
	tags = models.CharField(max_length=200, blank=True, null=True)
	updated_date = models.DateTimeField(auto_now=True)
	slug= models.SlugField(max_length=200, blank=True, null=True, unique=True)
	
	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('blog:drafts')

class Comment(models.Model):
	post = models.ForeignKey('blog.Post', related_name='comments', on_delete=models.CASCADE)
	author = models.ForeignKey('auth.User', on_delete=models.SET_NULL, null=True, blank=True)
	text = models.TextField()
	created_date = models.DateTimeField(auto_now_add=True)
	approved_comments = models.BooleanField(default=False)

	def approve(self):
		self.approved_comments = True
		self.save()

	def __str__(self):
		return self.text

class Tags(models.Model):
	tags = models.CharField(max_length=300)
	post = models.ForeignKey('blog.Post', related_name='tag_list', on_delete=models.CASCADE)

	def get_tag_list(self):
		return self.tags.split(',')

class Notifilcation(models.Model):
	reciever = models.ForeignKey('auth.User', on_delete=models.SET_NULL, null=True, related_name='revieved_notifications')
	sender = models.ForeignKey('auth.User', on_delete=models.SET_NULL, null=True, related_name='send_notifications')
	message = models.CharField(max_length=300, null=False, blank=False)
	comment = models.ForeignKey('blog.Comment', on_delete=models.CASCADE, null=True, related_name='comment_notifications')
	created_date = models.DateTimeField(auto_now_add=True)
	viewed_date = models.DateTimeField(null=True, blank=True)
	active = models.BooleanField(null=False, blank=False, default=True)
	message_type=models.CharField(max_length=10, null=True, blank=True, choices=MESSAGE_TYPE)

	def __str__(self):
		return self.message

class PostStats(models.Model):
	post = models.OneToOneField('blog.Post', related_name='stats', on_delete=models.CASCADE)
	last_view = models.DateTimeField(auto_now_add=True, null=True, blank=True)
	number_of_views = models.IntegerField(default=0)
	unique_viwes = models.IntegerField(default=0)

	def __str__(self):
		return self.post.title + ' (' + str(self.number_of_views) + ')'

	def add_num_view(self):
		self.number_of_views +=1

	def set_last_view(self):
		self.last_view = timezone.now()

	def set_unique_views(self):
		self.unique_viwes +=1


class UserViews(models.Model):
	user = models.ForeignKey('auth.User', related_name='user_views', on_delete=models.CASCADE, null=True)
	post = models.ForeignKey('blog.Post', related_name='blog_views', on_delete=models.CASCADE, null=True)
	view_date = models.DateTimeField(auto_now_add=True)

	def update_viewed_date(self):
		self.view_date = timezone.now()


class SubComment(models.Model):
	comment = models.ForeignKey('blog.Comment', on_delete=models.CASCADE, related_name='sub_comments')
	author = models.ForeignKey('auth.User', on_delete=models.SET_NULL, null=True)
	comment_text = models.TextField()
	created_date = models.DateTimeField(auto_now_add=True)
	updated_date = models.DateTimeField(auto_now=True)
	approved_comments = models.BooleanField(default=False)


'''
def comment_post_delete_receiver(sender, instance, created, *args, **kwargs):
	print("inside the signal function:", created)
	if instance:
		notifications = Notifilcation.objects.filter(comment=instance)
		if notifications:
			for notifilcation in notifications:
				notifilcation.delete()


post_delete.connect(comment_post_delete_receiver, sender=Comment)
'''

def blog_pre_save_receiver(sender, instance, raw, *args, **kwargs):
	if instance:
		instance.slug = slugify(instance.title)

pre_save.connect(blog_pre_save_receiver, sender=Post)

blog/forms.py
# forms.py

from django import forms
from blog.models import Post, Comment
from django.db.models import Q
from slugify import slugify

class PostForm(forms.ModelForm):

	post_id = forms.IntegerField(required=False)
	class Meta():
		model = Post
		fields = ('title', 'text', 'tags',)

	def clean(self):
		cleaned_data = super(PostForm, self).clean()

		if cleaned_data.get('title'):
			post_count = Post.objects.filter(
					Q(slug=slugify(cleaned_data.get('title')))
					| Q(title=cleaned_data.get('title'))).exclude(pk=cleaned_data.get('post_id')).count()
			if post_count:
				self.add_error('title', 'Post with similar title already exist. ' 
					+ 'Please confirm similar post not exist in the site.')

'''
		widgets = {
			'title' : forms.TextInput(attrs={'class':'textinputclass'}),
			'text'  : forms.TextInput(attrs={'class': 'editable medium-editor-textarea postcontent'})
		}

class CommentForm(forms.ModelForm):
	class Meta():
		model = Comment
		fields = ('text')

		widgets = {
			'text' : forms.TextInput(attrs={'class': 'editable medium-editor-textarea postcontent'})
		}
'''

blog/views.py
from django.shortcuts import render, render_to_response
from django.utils import timezone
from django.views.generic import (View, TemplateView, ListView, DetailView
									,CreateView, UpdateView, DeleteView)

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages

from django.urls import reverse, reverse_lazy
from django.views.generic.edit import ModelFormMixin
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect

from django.core import serializers
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.template import RequestContext
from django.db.models import Q
from django.contrib.auth.models import User

from blog.models import Post, Comment, Tags, PostStats, Notifilcation, UserViews, SubComment
from blog.forms import PostForm
from blog.serializer import CommentSerializer, PostSerializer

from slugify import slugify
import json
from blog.model_utils import ModelUtils

class HomeView(ListView):
	models = Post
	paginate_by = 3
	context_object_name = 'post_list'
	template_name = 'blog/home.html'

	def get_queryset(self):
		
		search = self.request.GET.get('search', '')
		if search:
			return Post.objects.filter(	Q(title__icontains=search) 
										| Q(text__icontains=search)
										| Q(tags__icontains=search), published_date__lte=timezone.now()).order_by('-published_date')
		else:
			return Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')



	def get_context_data(self, **kwargs):
		context = super(HomeView, self).get_context_data(**kwargs)
		search = self.request.GET.get('search', '')
		context['search'] = search
		context['page_name'] = 'blog_home'
		if self.request.user.is_authenticated:
			context['last_viewed'] = UserViews.objects.filter(user=self.request.user).order_by('-view_date')[:5]
		return context;

class DraftView(LoginRequiredMixin, ListView):
	model = Post
	template_name = 'blog/draft.html'

	def get_queryset(self):
		return Post.objects.filter(published_date__isnull=True, author=self.request.user).order_by('-created_date')

class DetailPostView(LoginRequiredMixin, DetailView):
	model = Post
	template_name="blog/view_post.html"
	slug_url_kwarg = 'slug'
	
	def get_context_data(self, **kwargs):
		context = super(DetailView, self).get_context_data(**kwargs)
		ModelUtils.update_blog_stats(context['object'], self.request.user)
		context['page_name'] = 'view_post'
		return context

class CreateBlogView(CreateView):
	template_name = 'blog/create_blog.html'
	form_class = PostForm

	def form_valid(self, form):
		self.obj = form.save(commit=False)
		self.obj.author = self.request.user
		self.obj.slug = slugify(self.obj.title)
		self.obj.save()
		return super(CreateBlogView, self).form_valid(form)


class DeletePostView(LoginRequiredMixin, View):
	
	def get(self,request, *args, **kwargs):
		post_id = kwargs.get('pk', '')
		context = {};
		if post_id:
			try:
				post = Post.objects.get(pk=post_id, author=request.user)
			except Post.DoesNotExist:
				post = ''
			if post:
				post.delete()
				context['success'] = 'Post deleted Successfully!!'
			else:
				context['error'] = 'Oops!!. Some error occured. :('
		else:
			context['error'] = 'Oops!!. Some error occured. :('
		return JsonResponse(context)

class GetDraftDetails(LoginRequiredMixin, View):
	def get(self, request, *args, **kwargs):
		draft_id = request.GET.get('draft_id', '')
		if draft_id:
			try:
				post = Post.objects.get(pk=draft_id, author=request.user)
			except Post.DoesNotExist:
				post = ''
			if post:
				return JsonResponse(serializers.serialize('json', [post], 
						fields=('title', 'text', 'author', 'created_date', 'tags')), safe=False)
			else:
				return JsonResponse({'error': 'Oops!!. Some error occured. :('})
		return JsonResponse({'error': 'Oops!!. Some error occured. :('})


class UpdateDraft(LoginRequiredMixin, UpdateView ):
	form_class = PostForm
	template_name = 'blog/draft.html'
	
	def get_object(self):
		return Post.objects.get(pk=self.request.POST.get('post_id'), author=self.request.user)

	def form_valid(self, form):
		self.obj=form.save()
		if self.request.POST.get('submit_type') == 'Post':
			self.obj.published_date = timezone.now()
			self.obj.save()
			messages.add_message(self.request, messages.SUCCESS, 'Draft Published Successfully..!!')
		else:
			messages.add_message(self.request, messages.SUCCESS, 'Draft Updated Successfully..!!')

		return super(UpdateDraft, self).form_valid(form)

	def form_invalid(self, form):
		messages.add_message(self.request, messages.SUCCESS, 'Oops Some Error Occured.. :)')
		return HttpResponseRedirect(reverse('blog:drafts'))

	def get_success_url(self):
		return reverse('blog:drafts')

class AddComment(LoginRequiredMixin, View):

	def post(self,request, *args, **kwargs):
		# print("\najax check: ", request.is_ajax())
		context = {};
		if request.POST.get('post_id') and request.POST.get('comment'):
			try:
				post = Post.objects.get(pk=request.POST.get('post_id'))
			except Post.DoesNotExist:
				post = ''
			if post:
				comment = Comment(post = post, author=request.user, text=request.POST.get('comment'))
				#if request.user == post.author:
				comment.approved_comments = True
				comment.save()

				if request.user != post.author:
					ModelUtils.add_notifications(request.user, post.author, 'new_comment', 
											comment=comment, post_title=post.title,)
				if request.POST.get('as_json'):
					serializer = CommentSerializer(instance=comment)
					context['log_user'] = request.user.pk
					context['post_author'] = post.author.pk
					context['comment'] = serializer.data
					return JsonResponse(context, safe=False)
				else:
					return render(request, 'blog/widgets/new_comment.html', {'comment':comment})
		return JsonResponse({'messages': 'Oops Some Error Occured.. :)'})

class CommentActions(LoginRequiredMixin, View):
	def post(self, request, *args, **kwargs):
		context ={};
		comment_id = request.POST.get('comment_id')
		user_action = request.POST.get('user_action')
		if (comment_id and user_action):
			try:
				comment = Comment.objects.get(pk=comment_id)
			except Comment.DoesNotExist:
				comment = ''

			if comment:
				if user_action == 'delete':
					if ((comment.author == request.user) or (comment.post.author == request.user)):
						comment.delete()
						context['delete'] = 1
				elif user_action == 'approve':
					if comment.post.author == request.user:
						comment.approve()
						context['approve'] = 1
						ModelUtils.add_notifications(request.user, comment.author, 'comment_approve', 
								title=comment.post.title, comment=comment)
				elif user_action == 'edit':
					if comment.author == request.user:
						context['edit'] = 1
						if request.POST.get('comment_text_update'):
							comment.text = request.POST.get('comment_text_update')
							comment.save() 
				return JsonResponse(context);
			else:
				return JsonResponse({'messages': 'Oops..Some error occured.. :('})
		return JsonResponse({'messages': 'Oops..Some error occured.. :('})

class MyTechBlogs(LoginRequiredMixin, ListView):
	template_name = 'blog/my_blogs.html'
	model = Post

	def get_queryset(self):
		return Post.objects.filter(author=self.request.user, published_date__isnull=False).order_by('-published_date')

class EditBlogView(LoginRequiredMixin, DetailView):
	template_name = 'blog/edit_blogs.html'
	model = Post
	fields = ('title', 'text', 'tags')

	def get_success_url(self):
		return reverse('blog:my_blogs')

class UpdateBlogView(LoginRequiredMixin, UpdateView):
	#template_name =
	model = Post
	fields = ('title', 'text', 'tags')
	template_name = 'blog/edit_blogs.html'

	def get_success_url(self):
		return reverse('blog:my_blogs')


class GetBlogTags(View):
	def get(self, request, *args, **kwargs):
		post_id = request.GET.get('post_id')
		if post_id:
			try:
				post = Post.objects.get(pk=post_id).tags
				tag_list = [tag.strip() for tag in post.split(',')]
				return JsonResponse({'tags': list(set(tag_list))})
			except Post.DoesNotExist:
				post = ''
		else:	
			post = Post.objects.all().values_list('tags')
			tag_list = []
			for row in post:
				if row[0]:
					tags = [tag.strip() for tag in row[0].split(',')]
					for tag in tags:
						if tag not in tag_list:
							tag_list.append(tag)
			return JsonResponse({'tags': tag_list[:50]})
		return JsonResponse({'error': 1})

class GetPostList(View):
	def get(self, request, *args, **kwargs):
		search_str = request.GET.get('search_text', '')
		if search_str:
			query_set = Post.objects.filter(title__icontains=search_str, published_date__isnull=False)
			searialie_data = PostSerializer(query_set, many=True)
			return JsonResponse(searialie_data.data, safe=False)
		else:
			return JsonResponse({})

class SubCommentActions(View, LoginRequiredMixin):
	
	def post(self, request, *args, **kwargs):
		comment_id = request.POST.get('comment_id')
		text = request.POST.get('text')
		sub_comment_id = request.POST.get('sub_comment_id')

		context = {}
		if sub_comment_id:
			action = request.POST.get('action')
			try:
				sub_comment = SubComment.objects.get(pk=sub_comment_id)
			except SubComment.DoesNotExist:
				sub_comment = None
				context['error'] = 1
			if sub_comment:
				if action == 'delete' and (sub_comment.author == request.user or sub_comment.comment.author == request.user):
					sub_comment.delete()
					context['success'] = 1
				elif action == 'edit' and sub_comment.author == request.user and text:
					sub_comment.comment_text = text
					sub_comment.save()
					context['success'] = 1
			else:
				return JsonResponse(context)
		else:
			try:
				comment = Comment.objects.get(pk=comment_id)
			except Comment.DoesNotExist:
				comment= None
			if comment:
				sub_comment = SubComment.objects.create(comment=comment, author=request.user, comment_text=text)
				if comment.author != request.user:
					ModelUtils.add_notifications(request.user, comment.author, 'sub_comment', comment=comment)

blog/templates/blog/about.html
<!--about.html -->
{% extends 'blog/base2.html' %}

{% block content %}
	<div class="container">
		<div class="card my-4">
			<h3 class="card-header">About</h3>
			<div class="card-body">
				<p><h4>Tech Blog</h4></p>
				<p>Hi, myself Kishor, I am a Software Engineer(works on <strong><i>Python, Perl, SQL, Javascript, jQuery etc..etc</i></strong>). Currently Exploring Django.
					This is a test blog created to practice Django. There may be errors on this
					If you find any errors or any suggestions, please inform me on <a href="mailto:kishorkrishnalayam@gmail.com">kishorkrishnalayam@gmail.com.</a></p>
				<p>Meanwhile please try my blog, you can post any blog after creating an account.</p>
				<p>Thank you for visiting.</p>
			</div>
		</div>
	</div>
{% endblock %}

blog/templates/blog/draft.html
<!-- draft.html -->

{% extends 'blog/base.html' %}

{% load static %}
{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<h1 class="my-4"><small>Drafts:</small></h1>
				<table class="table">
					<tr>
						<th>#</th>
						<th width="50%">Title</th>
						<th>Action</th>
					</tr>
					{% for draft in post_list %}
						<tr id="row_{{draft.pk}}">	
							<td>{{forloop.counter}}</td>
							<td>{{draft.title}}</td>
							<td>
								<span class="delete-img" id="delete_{{draft.pk}}"><i class="fa fa-close" style="font-size:20px;color:red"></i></span>&nbsp;
								<span class="edit-img" id="edit_{{draft.pk}}" data-toggle="modal" data-target="#myModal"><i class="fa fa-edit" style="color:blue"></i></span>
							</td>
						</tr>
					{% endfor %}
				</table>
			</div>
		</div>

		<div class="modal fade" id="myModal" role="dialog">
			<div class="modal-dialog modal-lg">
				<div class="modal-content">
					<div class="modal-header">
						<h4 class="modal-title">Update Your Post:</h4>
						<button type="button" class="close" data-dismiss="modal" aria-label="Close">
							<span aria-hidden="true">&times;</span>
						</button>
					</div>
					<form method="post" action="{% url 'blog:update_draft' %}">
						{% csrf_token %}
						<input type="hidden" name="post_id" id="post_id" value="">
						<input type="hidden" name="submit_type" id="submit_type" value="">
						<div class="modal-body">
							<div class="form-group">
								<label for="title">Title:</label>
								<input type="text" name="title" id="title" placeholder="Title" class="form-control"/>
								{% if form.title.errors %}
									<span style="color: red">{{form.title.errors}}</span>
								{% endif %}
							</div>
							<div class="form-group">
								<label for="text">Content:</label>
								<textarea class="form-control" name="text" id="text" rows="7"></textarea>
								{% if form.text.errors %}
									<span style="color: red">{{form.text.errors}}</span>
								{% endif %}
							</div>
							<div class="form-group">
								<label for="tags">Tags:
									<small>
										(should be comma separated values. You can select tags from available tags by clicking them.)
									</small>
								</label>
								<input type="text" name="tags" id="tags" placeholder="tags" class="form-control"/>
							</div>
						</div>
						<div class="modal-footer">
							<div class="form-group">
								<input class="btn btn-primary model-btn" type="submit" value="Save"/>
								<input class="btn btn-success model-btn" type="submit" value="Post"/>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
	<script type="text/javascript">
		{% if messages %}
			var message_text = '';
			{% for message in messages %}
				message_text += "{{message}} <br/>" 
			{% endfor %}
			display_popup_message(message_text, 'success');
		{% endif %}

		{% if form.title.errors %}
			$(document).ready(function(){
				var post_id = '{{form.post_id.value}}';
				if (post_id){
					$('#edit_'+post_id).click();
				}
			});
		{% endif %}

	</script>
	<script src="{% static "js/blog/draft_page.js" %}"></script>
{% endblock %}

blog/templates/blog/home.html
{% extends 'blog/base.html' %}

{% block content %}
	<h1 class="my-4">Latest Blogs
		<small></small>
	</h1>
	<!-- Blog Post -->
	{% if post_list %}
		{% for post in post_list %}
			<div class="card mb-4">
				<!--<img class="card-img-top" src="http://placehold.it/750x300" alt="Card image cap">-->
				<div class="card-body">
					<h2 class="card-title"><a href="{% url 'blog:post_details' slug=post.slug %}">{{post.title}}</a></h2>
					<p class="card-text">{{post.text|safe|linebreaks|truncatechars:300}}</p>
					<a href="{% url 'blog:post_details' slug=post.slug %}" class="btn btn-primary">Read More &rarr;</a>
				</div>
				<div class="card-footer text-muted">
				Posted on {{post.published_date|date:"M d, Y"}} by
				<a href="{% url 'user:user_details' slug=post.author.user_details.slug %}">{{post.author.first_name}}&nbsp;{{post.author.last_name}}</a>
				</div>
			</div>
		{% endfor %}
	{% else %}
		<div >
			Oops..!!! No post found :(
		</div>
	{% endif %}

	<!-- Pagination -->
	{% if is_paginated %}
		<ul class="pagination justify-content-center mb-4">
			{% if page_obj.has_previous %}
				<li class="page-item">
					<a class="page-link" href="?{% if search %}search={{search}}&{% endif %}page={{ page_obj.previous_page_number }}">&larr; Prev</a>
				</li>
			{% else %}
				<li class="page-item disabled">
					<a class="page-link" href="#">&larr; Prev</a>
				</li>
			{% endif %}

			{% if page_obj.has_next %}
				<li class="page-item">
					<a class="page-link" href="?{% if search %}search={{search}}&{% endif %}page={{ page_obj.next_page_number }}">Next &rarr;</a>
				</li>
			{% else %}
				<li class="page-item disabled">
					<a class="page-link" href="#">Next &rarr;</a>
				</li>
			{% endif %}
	{% endif %}
	<div>

	</div>
		<script type="text/javascript">
			
			$(document).ready(function(){
				$('#tag_header').html('Search with Tags')
				{% if messages %}
					var message_text = '';
					{% for message in messages %}
						message_text += "{{message}}<br/>"
					{% endfor %}
					$('#alert_div').html(message_text);
					$("#alert_div").fadeIn(1000).delay(1000).fadeOut(3000);
				{% endif %}

				$.ajax({
					type: 'get',
					url: '{% url "blog:get_tags" %}',
					data: {
						post_id: '',
					},
					success: function(response){
						console.log(response);
						if (response['tags']){
							tag1= [];
							tag2 =[];
							tags = response['tags'];
							for (var i=0; i< tags.length; i++){
								if (i%2 == 0){
									tag1.push(tags[i]);
								}else{
									tag2.push(tags[i]);
								}
							}
							append_tags(tag1, 'blog_tags1');
							append_tags(tag2, 'blog_tags2');
						}
					},
					error: function(response){

					},
				});
			});

			function append_tags(tags, id){
				field = '<ul class="list-unstyled mb-0">';
				for(var i=0; i< tags.length; i++){
					field+='<li><a href="?search='+ tags[i] + '">' + tags[i] + '</a></li>';
				}
				field+='</ul>'
				$('#'+id).html(field);
			}
		</script>
{% endblock %}

blog/templates/blog/my_blogs.html
<!-- my_blogs.html -->
{% extends 'blog/base.html' %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h1 class="my-4"><small>My Blogs:</small></h1>
			<table class="table">
				<tr>
					<th>#</th>
					<th>Title</th>
					<th>Action</th>	
				</tr>
				{% for post in post_list %}
					<tr id="row_{{post.pk}}">
						<td>{{forloop.counter}}</td>
						<td>
							<a data-toggle="tooltip" data-html="true" href="{% url 'blog:post_details' slug=post.slug %}"
							title="Nmber of views: {{post.stats.number_of_views}}
Last View:{{post.stats.last_view}}"
							>{{post.title}}</a>
						</td>
						<td>
							<span class="delete-img" id="delete_{{post.pk}}"><i class="fa fa-close" style="font-size:20px;color:red"></i></span>&nbsp;
							<a class="fa fa-edit" style="color:blue;cursor: pointer;" class="edit-img" href="{% url "blog:edit_blog" pk=post.pk %}"><span class="edit-img" id="edit_{{post.pk}}"></a></span>
						</td>
					</tr>
				{% empty %}
					<tr>
						<td colspan="3">No Posts available</td>
					</tr>
				{% endfor %}
			</table>
		</div>
	</div>
</div>
<script type="text/javascript">
	$(document).ready(function(){
		$('.delete-img').click(function(){
			var draft_id = $(this).attr('id').replace('delete_', '');
			if (confirm('Are you sure you want to delete this post?')){
				$.ajax({
					type: 'get',
					url: '/blog/delete_post/'+draft_id,
					//url: '{% url "blog:delete_post" pk=61 %}',
					success: function(response){
						if (response['error']){
							display_popup_message(response['error'], 'error');
						}else if (response['success']){
							display_popup_message(response['success'], 'success');
							console.log(response);
							$('#row_'+draft_id).remove();
						}else{
							console.log(response);
							display_popup_message('Oops Some error occured..!!', 'error');
						}
					},
					error: function(response){
						display_popup_message('Oops Some error occured..!!', 'error');
					}

				});
			}
		});
	});
</script>
{% endblock %}