blog/urls.py
# urls.py

from django.conf.urls import url, include
from blog import views

app_name = 'blog'

urlpatterns = [
	url(r'home', views.HomeView.as_view(), name='home'),
	url(r'about', views.AboutView.as_view(), name='about'),
	url(r'contactus', views.ContatView.as_view(), name='contactus'),
	url(r'notificatios', views.GetNotifications.as_view(), name='notofications'),
	url(r'get_fields', views.GetColumnData.as_view(), name='get_fields'),

	url(r'^post/post_list', views.GetPostList.as_view()),
	url(r'^post/(?P<slug>[-\w]+)$', views.DetailPostView.as_view(), name='post_details'),
	url(r'post/comment/add_comment$', views.AddComment.as_view(), name='add_comment'),
	url(r'post/comment/update_comment$', views.CommentActions.as_view(), name='update_comment'),
	url(r'^post/edit/(?P<pk>\d+)$', views.EditBlogView.as_view(), name='edit_blog'),
	url(r'^post/update/(?P<pk>\d+)$', views.UpdateBlogView.as_view(), name='update_blog'),
	url(r'post/comment/add_update_subcomment', views.SubCommentActions.as_view(), name='sub_comment'),

	url(r'create', views.CreateBlogView.as_view(), name='create'),
	url(r'drafts$', views.DraftView.as_view(), name='drafts'),
	url(r'delete_post/(?P<pk>\d+)$', views.DeletePostView.as_view(), name='delete_post'),
	url(r'draft_details', views.GetDraftDetails.as_view(), name='dtaft_details'),
	url(r'update_draft', views.UpdateDraft.as_view(), name='update_draft'),
	url(r'my_blogs', views.MyTechBlogs.as_view(), name='my_blogs'),
	url(r'^get_tags/', views.GetBlogTags.as_view(), name='get_tags'),
	

]

tech_blog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf.urls.static import static
from blog import urls
from user_auth import urls as auth_urls
from django.conf import settings
from blog import views
import blog


urlpatterns = [
    url(r'^$', views.HomeView.as_view()),
    path('admin/', admin.site.urls),
    url(r'blog/', include(urls)),
	url(r'user/', include(auth_urls))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'blog.views.handler404'
handler500 = 'blog.views.handler500'

user_auth/urls.py
#urls.py

from django.conf.urls import url
from user_auth import views

app_name = 'user'

urlpatterns = [
	url(r'login', views.LoginView.as_view(), name="login"),
	url(r'logout', views.LogoutView.as_view(), name="logout"),
	url(r'user_details/(?P<slug>[-\w]+)', views.UserDetailsView.as_view(), name="user_details"),
	url(r'update_password', views.UpdatePasswordView.as_view(), name="update_password"),
	url(r'register', views.RegisterView.as_view(), name="register"),
]

templates/common/footer.html
<!-- footer.html -->
{% load static %}
<!-- Bootstrap core JavaScript -->
<script src="{% static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>

<!-- Footer -->
<footer class="py-5 bg-dark">
  <div class="container">
    <p class="m-0 text-center text-white">Copyright &copy; TechBlog.com 2018</p>
  </div>
</footer>

templates/common/header.html
<!-- header.html -->
{% load static %}

<script type="text/javascript">
	var base_url = "{{request.get_host}}";
	var blog_url = base_url + '/blog';
</script>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title id="titleid">Blog Home</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static "vendor/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">
    <!-- <link rel="stylesheet" href="{% static "vendor/bootstrap/css/font-awesome.min.css" %}"> -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" rel="stylesheet">
    <link href="{% static "css/tech_blog.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static "css/blog-home.css" %}" rel="stylesheet">
    <script src="{% static "vendor/jquery/jquery.min.js" %}"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="{% static "js/tech_blog.js" %}"></script>
</head>

templates/common/messages.html
<!-- messages.html -->


<style type="text/css">
	.message-div {
		position: fixed;
		min-height: 60px;
		z-index: 22px;
		top: 70px;
		right: 20px;
		/*border: 1px solid;*/
	}
</style>

<div class="message-div" id="user_message_div">
	<div class="alert alert-success" role="alert" id="alert_div" style="display: none;">
	</div>
</div>

templates/common/navigation.html
<!-- navigation.html -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <a class="navbar-brand" href="{% url 'blog:home' %}">Tech Blog</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
      	{% if user.is_authenticated %}
	      	<li class="nav-item">
	          <a class="nav-link active" href="{% url 'blog:create' %}">New</a>
	        </li>
	    {% endif %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:home' %}">Home
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:about' %}">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:contactus' %}">Contact</a>
        </li>
        {% if request.user.is_authenticated %}
        	<li class="nav-item dropdown">
	          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	          	{% if request.user.first_name %}
	          		{{request.user.first_name}}
	          	{% elif request.user.last_name %}
	          		{{request.user.last_name}}
	          	{% else %}
	          		User
	          	{% endif %}
	          </a>
	          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
		          <a class="dropdown-item" href="{% url 'user:user_details' slug=request.user.user_details.slug %}">Profile</a>
		          <a class="dropdown-item" href="{% url 'blog:drafts' %}">Drafts</a>
		          <a class="dropdown-item" href="{% url 'blog:my_blogs' %}">My Blogs</a>
		          <div class="dropdown-divider"></div>
		          <a class="dropdown-item" href="{% url 'user:logout' %}">Logout</a>
		        </div>
	        </li>
        {% else %}
	        <li class="nav-item">
	          <a class="nav-link" href="{% url 'user:login' %}">Login</a>
	        </li>
	    {% endif %}
      </ul>
    </div>
  </div>
</nav>

<script type="text/javascript">
	$(document).ready(function(){
		$.ajax({
			type : 'get',
			url : '/blog/notificatios',
			data: {
					notification_type: 'all',
					
				},

			success: function(response){

			},

			error: function(response){

			}
		});
	});
</script>

templates/common/sidebar.html
<!-- sidebar.html -->

<div class="card my-4">
	<h5 class="card-header">Search</h5>
	<div class="card-body">
		<form method="get" action="{% url "blog:home" %}">
			<div class="input-group">
				<input type="text" class="form-control" placeholder="Search for..." name="search" id="search">
		    	<span class="input-group-btn">
		      		<button class="btn btn-secondary" type="submit" id="search-btn">Go!</button>
		    	</span>
		 	</div>
		 	<div>
		 		
		 	</div>
		</form>
	</div>
</div>

<!-- Categories Widget -->
<div class="card my-4">
	<h5 class="card-header" id="tag_header">Tags</h5>
	<div class="card-body">
	  <div class="row" id="divtag_body">
	    <div class="col-lg-6" id="blog_tags1">
	    </div>
	    <div class="col-lg-6" id="blog_tags2">
	    </div>
	  </div>
	</div>
	</div>

	{% if page_name == 'view_post' and request.user.is_authenticated and post.author.id == request.user.id %}
		<div class="card my-4">
			<h5 class="card-header">Details</h5>
			<div class="card-body">
				<table class="table">
					<tr>
						<td><b>Unique user views:</b></td>
						<td>{{ post.stats.unique_viwes }}</td>
					</tr>
					<tr>
						<td><b>Total views:</b></td>
						<td>{{ post.stats.number_of_views }}</td>
					</tr>
					<tr>
						<td><b>Last View:</b></td>
						<td>{{ post.stats.last_view|date:"M d, Y" }}</td>
					</tr>
				</table>
			</div>
		</div>
	{% endif %}

	{% if page_name == 'blog_home' and request.user.is_authenticated %}
		<div class="card my-4">
			<h5 class="card-header">Recent Views</h5>
			<div class="card-body">
				<ul>
				{% for view in last_viewed %}
					<li><a href="{% url 'blog:post_details' slug=view.post.slug %}">{{view.post.title}}</a></li>
				{% endfor %}
				</ul>
			</div>
		</div>
	{% endif %}
</div>

<script type="text/javascript">



	function monkeyPatchAutocomplete() {

		// don't really need this, but in case I did, I could store it and chain
		var oldFn = $.ui.autocomplete.prototype._renderItem;

		$.ui.autocomplete.prototype._renderItem = function( ul, item) {
		var re = new RegExp("" + this.term) ;
		var t = item.label.replace(re,"<span style='font-weight:bold;color:Blue;'>" + 
		this.term + 
			"</span>");
			return $( "<li></li>" )
			.data( "item.autocomplete", item )
			.append( "<a>" + t + "</a>" )
			.appendTo( ul );
		};
	}

	$(document).ready(function(){
		monkeyPatchAutocomplete();
	});

	$('#search').keyup(function(){
		var text = $(this).val();
		if (text){
			$.ajax({
				type: 'get',
				url: '/blog/post/post_list',
				data: {
					search_text: text,
				},

				success: function(response){
					sourceData = [];
					for (var i=0; i< response.length;i++){
						sourceData.push(response[i]['title']);	
					}
					$( "#search" ).autocomplete({
						source: sourceData,
						classes: {
							"ui-autocomplete": "highlight"
						},
						select: function(event, ui){
							console.log(ui['item']['label']);
							$('#search').val(ui['item']['label']);
							$('#search-btn').click();
						},
					});			
				},

				error: function(response){

				},

			});
		}
	});
	$( function() {
	
});
</script>