blog/urls.py
# urls.py

from django.conf.urls import url, include
from blog import views

app_name = 'blog'

urlpatterns = [
	url(r'home', views.HomeView.as_view(), name='home'),
	url(r'about', views.AboutView.as_view(), name='about'),
	url(r'contactus', views.ContatView.as_view(), name='contactus'),
	url(r'notificatios', views.GetNotifications.as_view(), name='notofications'),
	url(r'get_fields', views.GetColumnData.as_view(), name='get_fields'),

	url(r'^post/post_list', views.GetPostList.as_view()),
	url(r'^post/(?P<slug>[-\w]+)$', views.DetailPostView.as_view(), name='post_details'),
	url(r'post/comment/add_comment$', views.AddComment.as_view(), name='add_comment'),
	url(r'post/comment/update_comment$', views.CommentActions.as_view(), name='update_comment'),
	url(r'^post/edit/(?P<pk>\d+)$', views.EditBlogView.as_view(), name='edit_blog'),
	url(r'^post/update/(?P<pk>\d+)$', views.UpdateBlogView.as_view(), name='update_blog'),
	url(r'post/comment/add_update_subcomment', views.SubCommentActions.as_view(), name='sub_comment'),

	url(r'create', views.CreateBlogView.as_view(), name='create'),
	url(r'drafts$', views.DraftView.as_view(), name='drafts'),
	url(r'delete_post/(?P<pk>\d+)$', views.DeletePostView.as_view(), name='delete_post'),
	url(r'draft_details', views.GetDraftDetails.as_view(), name='dtaft_details'),
	url(r'update_draft', views.UpdateDraft.as_view(), name='update_draft'),
	url(r'my_blogs', views.MyTechBlogs.as_view(), name='my_blogs'),
	url(r'^get_tags/', views.GetBlogTags.as_view(), name='get_tags'),
	

]

tech_blog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf.urls.static import static
from blog import urls
from user_auth import urls as auth_urls
from django.conf import settings
from blog import views
import blog


urlpatterns = [
    url(r'^$', views.HomeView.as_view()),
    path('admin/', admin.site.urls),
    url(r'blog/', include(urls)),
	url(r'user/', include(auth_urls))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'blog.views.handler404'
handler500 = 'blog.views.handler500'

user_auth/urls.py
#urls.py

from django.conf.urls import url
from user_auth import views

app_name = 'user'

urlpatterns = [
	url(r'login', views.LoginView.as_view(), name="login"),
	url(r'logout', views.LogoutView.as_view(), name="logout"),
	url(r'user_details/(?P<slug>[-\w]+)', views.UserDetailsView.as_view(), name="user_details"),
	url(r'update_password', views.UpdatePasswordView.as_view(), name="update_password"),
	url(r'register', views.RegisterView.as_view(), name="register"),
]

user_auth/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from slugify import slugify


# Create your models here.

class UserDetails(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_details')
	middle_name = models.CharField(max_length=100, blank=True, null=True)
	slug = models.SlugField(max_length=200, blank=True, null=True, unique=True)

	def __str__(self):
		return str(self.user.first_name) + "::" + str(self.slug)

'''
def user_post_save_receiver(sender, instance, created, *args, **kwargs):
	print("inside the signal function:", created)
	if created:
		UserDetails.objects.create(user=instance, middle_name='', slug=slugify(instance.username))



post_save.connect(user_post_save_receiver, sender=User)
'''

user_auth/forms.py
#forms.py

from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.password_validation import validate_password
from django.core.exceptions import ValidationError
from slugify import slugify
from user_auth.models import UserDetails

class UserForm(forms.ModelForm):
	email = forms.EmailField(required=True)
	first_name = forms.CharField(required=True)
	last_name = forms.CharField(required=True)
	middle_name = forms.CharField(required=False)
	class Meta():
		model = User
		fields = ('email', 'first_name', 'last_name')

class LoginForm(forms.Form):
	username = forms.CharField(required=True)
	password = forms.CharField(required=True)


class PasswordForm(forms.Form):
	password = forms.CharField(required=True)
	new_password = forms.CharField(required=True)
	confirm_password = forms.CharField(required=True)

	def clean(self):
		form_data = super().clean()
		if form_data.get('new_password') != form_data.get('confirm_password'):
			self.add_error('new_password', 'New and confirm password doesnot match..!!');

class RegisterForm(forms.ModelForm):
	first_name = forms.CharField()
	last_name = forms.CharField()
	email = forms.CharField()
	password = forms.CharField(required=True)

	class Meta():
		model = User
		fields = ('username', 'first_name', 'last_name', 'email', 'password',)

	def clean(self):
		clean_data = super(RegisterForm, self).clean()
		password = clean_data.get('password')
		if password:
			try:
				validate_password(password)
			except ValidationError as e:
				print(str(e))
				self.add_error('password', '<br/>'.join(e))

		if clean_data.get('username'):
			try:
				user_details = UserDetails.objects.get(slug=slugify(clean_data.get('username')))
			except:
				user_details= None

			if user_details:
				self.add_error('username', 'username already exist. Please chooes a different username.')

user_auth/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordChangeForm
from django.views.generic import View, UpdateView, CreateView
from django.contrib import messages
from user_auth.forms import LoginForm, UserForm, PasswordForm, RegisterForm
from user_auth.models import UserDetails
from django.conf import settings
from slugify import slugify


# Create your views here.

class LoginView(View):
	template_name = 'user_auth/login.html'
	context = {}

	def post(self, request):
		form = LoginForm(request.POST)

		if form.is_valid():
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']

			user = authenticate(username=username, password=password)
			if user:
				if user.is_active:
					login(request, user)
					messages.add_message(request, messages.SUCCESS, "Welcome "+str(request.user.first_name)+ '!!')
					return HttpResponseRedirect(reverse('blog:home'))
				else:
					self.context['error'] = 'This user is inactive'
			else:
				self.context['error'] = 'Invalid username or password.'	
		else:
			self.context['error'] = 'Please enter username and password.!!'
		return render(request, self.template_name, self.context)

	def get(self, request):
		if request.user.is_authenticated:
			return HttpResponseRedirect(reverse('blog:home'))
		return render(request, 'user_auth/login.html')

class LogoutView(View):
	def get(self, request):
		logout(request)
		messages.add_message(request, messages.SUCCESS, "Successfully logged out. See you again!!")
		return HttpResponseRedirect(reverse('blog:home'))

class UserDetailsView(LoginRequiredMixin, UpdateView):
	model = User
	template_name = 'user_auth/user_details.html'
	form_class = UserForm

	def get_object(self, queryset=None):
		slug = self.kwargs.get('slug', None)
		try:
			return User.objects.get(user_details__slug= slug)
		except User.DoesNotExist:
			return ''

	def form_valid(self, form):
		self.object = form.save()
		try:
			userdetails = UserDetails.objects.get(user=self.object)
		except UserDetails.DoesNotExist:
			userdetails = ''

		if userdetails:
			userdetails.middle_name = form.cleaned_data.get('middle_name')
			userdetails.save()
		messages.add_message(self.request, messages.SUCCESS, "Profile updated successfully..!!")
		return super(UserDetailsView,self).form_valid(form)
	
	def get_success_url(self):
		return reverse('blog:home')

class UpdatePasswordView(LoginRequiredMixin, View):

	def post(self, request):
		
		form = PasswordChangeForm(request.user, request.POST)
		if form.is_valid():
			user = form.save()
			update_session_auth_hash(request, user)
			return JsonResponse({'success': 1, 'message': 'Password updated successfully.. :)'})
		else:
			print(form.errors.as_json())
			return JsonResponse({'error': 1, 'message': 'Oops..! Update failed.. Please fix the errors', 'form_errors': form.errors.as_json()})


class RegisterView(CreateView):
	form_class = RegisterForm
	template_name = 'user_auth/register.html'

	def form_valid(self, form):
		print(form.cleaned_data['first_name'])
		self.obj = form.save(commit=False)
		self.obj.set_password(form.cleaned_data['password'])
		self.obj.save()
		if self.obj.username:
			# add user details data
			UserDetails.objects.create( user=self.obj, 
											middle_name=form.cleaned_data.get('middle_name'), 
											slug=slugify(self.obj.username))

			current_user = authenticate(username=self.obj.username, password=form.cleaned_data['password'])
			login(self.request, current_user)
			messages.add_message(self.request, messages.SUCCESS, 'Welcome '+ current_user.first_name)
		else:
			messages.add_message(self.request, messages.SUCCESS, 'Oops..!! Some error occured..!!')
		return super(RegisterView, self).form_valid(form)

	def get_success_url(self):
		return reverse('blog:home')

user_auth/templates/user_auth/login.html
<!--login.html -->
<style type="text/css">
	.form-signin
{
    max-width: 330px;
    padding: 15px;
    margin: 0 auto;
}
.form-signin .form-signin-heading, .form-signin .checkbox
{
    margin-bottom: 10px;
}
.form-signin .checkbox
{
    font-weight: normal;
}
.form-signin .form-control
{
    position: relative;
    font-size: 16px;
    height: auto;
    padding: 10px;
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
}
.form-signin .form-control:focus
{
    z-index: 2;
}
.form-signin input[type="text"]
{
    margin-bottom: -1px;
    border-bottom-left-radius: 0;
    border-bottom-right-radius: 0;
}
.form-signin input[type="password"]
{
    margin-bottom: 10px;
    border-top-left-radius: 0;
    border-top-right-radius: 0;
}
.account-wall
{
    margin-top: 20px;
    padding: 40px 0px 20px 0px;
    background-color: #343a40 !important;
    -moz-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
    -webkit-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
    box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
}
.login-title
{
    color: #555;
    font-size: 18px;
    font-weight: 400;
    display: block;
}
.profile-img
{
    width: 96px;
    height: 96px;
    margin: 0 auto 10px;
    display: block;
    -moz-border-radius: 50%;
    -webkit-border-radius: 50%;
    border-radius: 50%;
}
.need-help
{
    margin-top: 10px;
}
.new-account
{
    display: block;
    margin-top: 10px;
}
</style>
{% extends 'blog/base2.html' %}

{% block content %}
<div class="container">
    <div class="row" style="margin-top: 20px;">
    	<div class="col-md-5"></div>
        <div class="col-md-7">
            <h1 class="text-center login-title">Sign in to continue to TechBlog</h1>
            <div class="account-wall">
                <img class="profile-img" src="https://lh5.googleusercontent.com/-b0-k99FZlyE/AAAAAAAAAAI/AAAAAAAAAAA/eu7opA4byxI/photo.jpg?sz=120"
                    alt="">
                <form class="form-signin" method="post">
                	{% csrf_token %}
                <input name ="username" type="text" class="form-control" placeholder="Email" required autofocus>
                <input name="password" type="password" class="form-control" placeholder="Password" required>
                <button class="btn btn-lg btn-primary btn-block" type="submit">
                    Sign in</button>
                <label class="checkbox pull-left">
                    <input type="checkbox" value="remember-me">
                    <span class="text-white">Remember me</span>
                </label>
                <a href="#" class="pull-right need-help">Need help? </a><span class="clearfix"></span>
                </form>
                {% if error %}
                	<p style="color: red;text-align: center">{{error}}</p>
                {% endif %}
            </div>
            <a href="{% url 'user:register' %}" class="text-center new-account">Create an account </a>
        </div>
        
    </div>
</div>
{% endblock %}

user_auth/templates/user_auth/register.html
<!-- register.html -->

{% extends 'blog/base2.html' %}

{% block content %}
	<div class="container">
		<div class="row" style="margin-top: 20px;">
			<div class="col-md-4"></div>
			<div class="col-md-8">
				<form class="form-signin" method="post">
                	{% csrf_token %}
                	<div class="form-group">
						<label for="first_name">Username:</label>
						<input type="text" name="username" id="username" placeholder="username" class="form-control"
						value="{{form.username.value|default_if_none:""}}"/>
						{% if form.username.errors %}
							<span style="color: red">{{form.username.errors}}</span>
						{% endif %}
					</div>

					<div class="form-group">
						<label for="first_name">First Name:</label>
						<input type="text" name="first_name" id="first_name" placeholder="First Name" class="form-control" value="{{form.first_name.value|default_if_none:""}}"/>
						{% if form.first_name.errors %}
							<span style="color: red">{{form.first_name.errors}}</span>
						{% endif %}
					</div>

					<div class="form-group">
						<label for="last_name">Last Name:</label>
						<input type="text" name="last_name" id="last_name" placeholder="Last Name" class="form-control"
						value="{{form.last_name.value|default_if_none:""}}"/>
						{% if form.last_name.errors %}
							<span style="color: red">{{form.last_name.errors}}</span>
						{% endif %}
					</div>

					<div class="form-group">
						<label for="first_name">Email:</label>
						<input type="text" name="email" id="email" placeholder="Email" class="form-control"
						value="{{form.email.value|default_if_none:""}}"/>
						{% if form.email.errors %}
							<span style="color: red">{{form.email.errors}}</span>
						{% endif %}
					</div>
					<div class="form-group">
						<label for="first_name">Password:</label>
						<input type="password" name="password" id="password" placeholder="Password" class="form-control"
						value=""/>
						{% if form.password.errors %}
							<span style="color: red">{{form.password.errors}}</span>
						{% endif %}
					</div>
					<div>
						<input type="submit" name="submit" class="btn btn-success" value="Register">
					</div>
					<br/>
                </form>
			</div>
		</div>
	</div>
{% endblock %}

user_auth/templates/user_auth/user_details.html
<!-- user_details.html -->

{% extends 'blog/base2.html' %}

{% block content %}
	<div class="container" style="margin-top: 10px;margin-bottom: 10px;">
		<div class="col-md-12">
			<h3>Profile:</h3>
			{% if user.pk == request.user.pk %}
				<form method="post">
					{% csrf_token %}
					<div class="form-group">
						<label for="first_name">First Name:</label>
						<input type="text" name="first_name" id="first_name" placeholder="First Name" class="form-control"
						value="{{request.user.first_name}}"/>
						{% if form.first_name.errors %}
							<span style="color: red">{{form.first_name.errors}}</span>
						{% endif %}
					</div>
					<div class="form-group">
						<label for="last_name">Middle Name:</label>
						<input type="text" name="middle_name" id="last_name" placeholder="Middle Name" class="form-control"
						value="{{request.user.user_details.middle_name}}"/>
						{% if form.middle_name.errors %}
							<span style="color: red">{{form.middle_name.errors}}</span>
						{% endif %}
					</div>
					<div class="form-group">
						<label for="last_name">Last Name:</label>
						<input type="text" name="last_name" id="last_name" placeholder="Last Name" class="form-control"
						value="{{request.user.last_name}}"/>
						{% if form.last_name.errors %}
							<span style="color: red">{{form.last_name.errors}}</span>
						{% endif %}
					</div>
					<div class="form-group">
						<label for="email">Email:</label>
						<input type="text" name="email" id="email" placeholder="Email" class="form-control" value="{{request.user.email}}"/>
						{% if form.email.errors %}
							<span style="color: red">{{form.email.errors}}</span>
						{% endif %}
					</div>
					<div>
						<input type="submit" name="submit" class="btn btn-success" value="Save">
					</div>
				</form>
			{% else %}
				<br/>
				<table class="table">
					<tr>
						<td><strong>First Name</strong></td>
						<td>{{user.first_name}}</td>
					</tr>
					<tr>
						<td><strong>Middle Name</strong></td>
						<td>{{user.user_details.middle_name}}</td>
					</tr>
					<tr>
						<td><strong>Last Name</strong></td>
						<td>{{user.last_name}}</td>
					</tr>
					<tr>
						<td><strong>Email</strong></td>
						<td>{{user.email}}</td>
					</tr>
				</table>
			{% endif %}
		</div>
	</div>
{% endblock %}

{% block sidebar %}
	<div class="card my-4">
		<h5 class="card-header">Details</h5>
		<div class="card-body">
		  <div class="row">
		  	<div class="col-lg-12">
		  		<div class="container">
			  		<p><strong>Last Login: </strong>{{user.last_login}}</p>
			  		<!--<p><strong>User Actions:</strong></p>-->
		  		</div>
		  	</div>
		  </div>
		</div>
	</div>
	{% if user.pk == request.user.pk %}
		<div class="card my-4" id="update_passowrd_div">
			<h5 class="card-header">Update Password</h5>
			<div class="card-body">
			  <div class="row">
			  	<div class="col-lg-12">
			  		<div class="container">
				  		<div class="form-group">
							<label for="old_password">Current Password:</label>
							<input type="password" name="old_password" id="old_password" class="form-control"/>
						</div>
			  		</div>
			  		<div class="container">
				  		<div class="form-group">
							<label for="new_password1">New Password:</label>
							<input type="password" name="new_password1" id="new_password1" class="form-control"/>
						</div>
			  		</div>
			  		<div class="container">
				  		<div class="form-group">
							<label for="new_password2">Confirm Password:</label>
							<input type="password" name="new_password2" id="new_password2" class="form-control"/>
						</div>
			  		</div>
			  		<div style="text-align: center">
			  			<input type="button" name="update_passowrd" id="update_passowrd" value="update" class="btn btn-primary">
			  		</div>
			  	</div>
			  </div>
			</div>
		</div>

		<script type="text/javascript">
			$(document).ready(function(){
				$('#update_passowrd').click(function(){
					$.ajax({
						type: 'post',
						url: "{% url 'user:update_password' %}",
						data: { old_password: 		$('#old_password').val(),
								new_password1: 	$('#new_password1').val(),
								new_password2: $('#new_password2').val(),
								csrfmiddlewaretoken: $('input[name="csrfmiddlewaretoken"]').val(),
							  },
						success: function(response){

							if (response['error']){
								display_errors(response['form_errors'], 'update_passowrd_div');
							}else{
								$('#update_passowrd_div .field-error').remove();
								display_popup_message(response['message'], 'success');
							}
						},

						error: function(response){
							console.log(response);
						}

					});
				});
			});
		</script>
	{% endif %}
{% endblock %}